version: '3'
services:
  rabbitmq:
    image: arm32v7/rabbitmq:management
    container_name: "rabbitmq"
    restart: always
    logging:
        driver: "${LOGGING_DRIVER:-json-file}"
    network_mode: "host"
    ports:
        - 8080:15672
    #command: 
    #     redis-server /usr/local/etc/redis/redis.conf
    #volumes:
    #     - ./redis.conf:/usr/local/etc/redis/redis.conf
#        - /var/run/docker.sock:/var/run/docker.sock
